export const STAFF_INIT = 'STAFF_INIT';
export const STAFF_FETCHED = 'STAFF_FETCHED';
export const STAFF_ADDED = 'STAFF_ADDED';
export const STAFF_UPDATED = 'STAFF_UPDATED';
export const STAFF_REMOVED = 'STAFF_REMOVED';
export const STAFF_ERROR = 'STAFF_ERROR';


//companies constant
export const COMPANY_INIT = 'COMPANY_INIT';
export const COMPANY_FETCHED = 'COMPANY_FETCHED';
export const COMPANY_ADDED = 'COMPANY_ADDED';
export const COMPANY_UPDATED = 'COMPANY_UPDATED';
export const COMPANY_REMOVED = 'COMPANY_REMOVED';
export const COMPANY_ERROR = 'COMPANY_ERROR';

//attraction constant
export const ATTRACTION_INIT = 'ATTRACTION_INIT';
export const ATTRACTION_FETCHED = 'ATTRACTION_FETCHED';
export const ATTRACTION_ADDED = 'ATTRACTION_ADDED';
export const ATTRACTION_UPDATED = 'ATTRACTION_UPDATED';
export const ATTRACTION_REMOVED = 'ATTRACTION_REMOVED';
export const ATTRACTION_ERROR = 'ATTRACTION_ERROR';

export const ROLES_INIT = 'ROLES_INIT';
export const ROLES_FETCHED = 'ROLES_FETCHED';
export const ROLES_ADDED = 'ROLES_ADDED';
export const ROLES_UPDATED = 'ROLES_UPDATED';
export const ROLES_REMOVED = 'ROLES_REMOVED';
export const ROLES_ERROR = 'ROLES_ERROR';